---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-rest-api-validator
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: PawYQ2dFpSW9A1hH81IFPuzX968FVDbsKAL97TgGWGiW4utV8wkcla+n+Lz5X1Cehnw=
---
kind: secret
name: docker_password
data: gtXL+jCqTzTTeinX8n4TDeAxw8F7L3RWMSmtNECDOnbNyz5o60AXhXSZfgOIf0+7ftwXmJPF7WJkhQbbaaX9yS63BiNNkMPj1Ne7pxtVgt3gbRE2nfeC9xk6sdc=
---
kind: secret
name: ssh_key
data: 4Rz2irBGIBNcSlt4lYNwvGFvtPrwfzF8a/HDj09MR9eFLC0Tcky0vX10a8QBjBpuLN8PEuHJfRwKSre0gCBzwFdoEWC+NWXoinSuYXWUa2jGpTH9MbStKwhFASY+PfrzlzmWBwdNWU6XlQ1fPU2+BBHNwnOCJeFidYbMXezOijNpuzHdn77QpkDDr0YVXT7ZXrW8ZN2aV7rzdwWWQFNZc6/0o2/3778yRZ78jRapSLfOI4vIVgFLCw4GzlGPAYeaJYsL24KZvEH55MR5DDasa3qW4GVoZ4u2OnhJFgdZMopQ+jVk9sBVl7oobAK8nYCKOxq8mlyNR77b5V4oL4yScuBx/yu5GMujEyZoSe1hWKHG+ZoeG1DODN7zKRMenLwro0gGSpLdUD5FtT8isADhiRvV8GWcq88drHhOQsDtBhun5zhuH8AAGNNa+qfRe1Q6GBl23/jxE33VNGQlCodjJReJm/MJwn0NWoRwxAFnTu2Taky+6l7XzrdSIx+Ahy2IfJlHtI9pCD2Sl/IByoZsng3qQ4JglfER5wzjJHxPgDbVF893w1AJ42zQtCkUClQ4uB+DwBT4AFpNor5FRk085mWR/EWrjG9TSPFIOgpSpp/nZUIARRzI4nsLEKAYNoGdc0NBtgjkHi148nHLRWpIfMentmmG/NpoWt2lqLB4/46epi/MWy1y0zyTyATrKzQcUUEf9Ka5qhQV9IlNv9NSdAE4Fbj0q84aWZrq8xbc/vMozPsahY9PnHrM8ohaxprRAWF2TPup+DsTZ77s4EsVikCvWW+/AM0SeJALwBNJQiXbjUGEzbw+X/i4TvxSfg5e4Mn1bJZNQC84Isv6RRWwr66zyNplBBFaRHpoFWgykrswhbRgbkP0WcFz6u/Rsyb6XqZ7nuWfI3YKovLFmCHYSLV1aQR9MJEIFczRBvzYiqURKG/hCgGS+Hy5pm/MokjwpVomiU1P8aaIEyvAYV4adr5I3Z8Uh7lk51k7uBHLYm5mcKGDuYub7AnU5Mow/iis0eZBFfzM/dxMbxbXDt6qyY/akTf8iS9xAV37imLFnZnYlXCB4TVp+NtAS1TsBAOAvMrzkKkYX8Sr4VCkt26FpAgz8AUsDmdvp0232GAWfYhySVVyjGxj3sP+E1ZvRTvQlVILwnsMvxXU+QpDxUE6GTW0vpubcqJsCnjiz99KZpZWmbUoRVEAnk43bdAoRJy1E4lOp9JfAL4KZYPTtw0zThy6wXV+B64e/MXqLWmkPF5U3WQuLxjTF4YAfVSosw53i4oQ4COBP+f5VX9btO6H2poNiCBoE0L2HHa7vpoJ9Xj+ZhMzHwWnHFZHdJjRWLcie1Mdzvv5CF9VClj/LHXsBOO1BGhC/2octjiGjo1kjPUYCP9GUFYDzJZeM53BiRdIjySjou1J2JZj5T9cpOrRrM70Ya3VvBwZYcwjnJgQixY8WTwJcXixts4qOqE/rKYxv5zu4V21i44uxQzMK969gSLtJZcwayKiZ1TxyrUf/+9lE44DA2E8Om8Kike2vS81oqss3nJtWumob53WbBNaRY84wgDJA4n4lOIWscqAAtVsjmCEWypnGXcKloYo+6drkzzl25PhK1zISI8NrSsu7FJUlnZYiH6myHLe9NhF3sjDIpmEZPxuUdHNcVcwtkCUOszuMO9AD2AILSsesrCEecQDZTmw00deNkIBYwqR2C7xlMUVXvGWH/OHru78D+2BLRbLtFq7wAWQL/uxG78cMqnQcdvZwjT8mUbmxHGqjnhx5YlanL1tHRA2x1S61kyQZGkpkDRp/ZLHn3hdIQE15vWJYob1jBYRJJEaw7dKidw49FjmfMhROW/ajzTQfvTQzdu7VOd50W3YZxHq8FfhdDFZE3lhqlHabUZfPjkXtT2UeP71EJZFN6efwUXgWu9NNC9W9AaQ0p/lkwCPqBAQYHQwPoQMBFzBFoIQIG/RMSSCbDWKRsIn3ebyUOBRl/UelEAa9OVf9aXQPIEKM51gXz9UAF649hgDmkVPNWQwL3rrHclKrqQFg8BGVAcS6EPi/yhB/aCWOQZIuANEB3OCTkrQCMtBqps6OJU5im5+wiytBLgM6bM+hrDnk/kCdZk75fzYoKUqS5Ti+ZSyVRBsKqxgpfKZj6J1NUMnrpD7Fq3Pb6J4EMJxtZwzf8EV8jIJjyVGeuY/jE15Mgym1epQEl4sq8KSjJWarzrf9WLO6uXLdcpJBJVHyjc3IzwGtKPIJmuWoE5oyfa9B6dWyWYaUYTNdePK6ofpgm2AtlMQUwn0tUeBzXlBLFE3wH3qCZkjVOscWPRorUXHf6QTcSH9+oHsQx0cYbOcZcdedQ3GpmX6wvp6qKnQs6K1Z8/qQvub56Wz9tHvOJ53fGqW/O1BwKq6K2Hu6SuVnWjjxJ53QESGe/JGVSwhQeCNZNE1BJkkByoPLLcCta4lmFDUuLiihoj8EOZ9oipRwXQCL0oaukIPscOkDhDXu1fkDOL/IeCqGcsTfGXU2MchooCI2XF0uCFC+o3AvrDhD9kmEDDP6MS/W1ritkjP4nMlIMNfFigjomIM/EhCQELmticnYc507gm/i4/491yG19ikedWP3of1KW837+oeAWFQLeAf+Qd26j5KruUAt2+b8IprVTCT0Yt+B6iX8UVz6sqDX+tAKuCXEuBNH+9Y2TZ5XeKVe1yVZVomLdgx3kRnDG3I0Ru0DPndVy3LzcU2eX8xb5JHaWB6CzO1+qvYEK6B0oGBVBeaSe2ApAwukXYPL5xWaVF7o/Q+agWpbHP2hit6WA5uRu1tSkDFsiaHPU4BvHlx+eixpCawTa/3i6ckFNRVl9Epz0VeUo/9VFA0myAhbuQ5w2oOSWop0l3gC7BNiA0gTy0rbMI8f8MD2SaJ6dQx+7zIzg4wEwmk70wK2VyR/jG4MuakMfRg5XTNaLrg5WXYoS4SywXoP5T45D8OyMnKp034kKpjZBDsuUwT3BB/Qg+dTlk/ejaaE4SIOetOYsUYgaOw2KpwdqSkneGDIngI
---
kind: secret
name: gpg_key
data: UIvHoG9lKno8pG/y1KqDxrwd+0XSh28QuRMK+EJXI0B4o5gKIjZnykuLE2/mHnH3xxJoVrm4X2raCjtkzww6i59kzmlsnlWfiz2ZSvrBSUkSKEbs65sa90jmfLTbx+fSULeex3zI0k2tR76E1ByBM3TX+v55E/JAabNsdFj+uN6SODMPGfCEgOFT57Ubxz06qVLXN4eMVL5clxrom9h3y/Ft27AXo6acGq6zOqlVm+IGc0651cXecVXN2/ebVH0mXGDI8QUtCqUC1hB2/K6G8IBqHIsQOTqVsIogykcs2HjYpNfYIulg/exfA9Ic2Lslik2wlax6WgqG537iRZrH5vnOhlLKKC4K6aSGtW9IHlZVYZ+VfL+LvIdqXyosHZYN67MWk9caiUkZKyWDV6ybMkW0UXEYokPNuBK9O1feifQPYQ8ei3iuYwn9L3ExWxCnH8c+iQcF+EXVJgtrseYNlic399m7OHq+LYruvrenmcYelAUV1r/tBuP2p8U6mkWUrvb+StAF9hO4i34StcvqvYp6h6uIFrLndht3pzTqSWabg+yHv442WgQtic2tVkdfk9vHT47/XIzpSEJhEhndvIWbbAsx45kkLejXOLRjHc5s0bgdLKzCrWlSJD0wwrkj2aCUdLXRiftArO+XC8Avtnu2D/Xf3ggf/JPdKb/9Ze08jv4TwsEYDybb4b145iA/Glm2X6FeOKP9rn2BdlWWod8UyDkAtjqAfaTuE6x7vacXGSJByNbl6whjjXscod1prxgRbVF5FZSGgYOPN3rqsdzu2/EvScI7UilgGU1p33RZFRjetXfcVXTv1/tJtMWgoqloIr/cM7cVPBxFX+GoGAlF7wHCxb47tFtcKXYwIRWQX9XR4/yagpyVHkyZDotsQUc0FPd1v8ytpsldKnUKE1z8uD5zPE4v7IvE8nOs0O4yHQnaHYiFbuLK81YVoFDP9JMnUETZ99t8oHgTBvybDk1U22dKdbYdK39dAAENWfIcwt92CugxFuERyU772VGLM8JG+nTzFI0g7Km3wlOORoEJ5gCAZT+hbTfvg7gzyWWJ3gM16lXx9qreBJyIwut0udRiS0+/0G/RlGHhVoUvBmUrgXFdbq8GyLlJPmyorDJuc0N1ztFQjEEBrk03n8nrd7RugsqkGSSlUipfJxNs8QXz9JyrdxjnJoC4ZRwHhMV0DMx2dFuCzBZEOj318nkFzfeFT1XL+l/T6e3HBsIO8vdi8YxsnbPnYJn4UhJa4ThCepjgn3tZzr71rcGuqdVq1iyH8wzrKkMPbYzj2RdpiVDYOfrOyhfRrl4D+CLdI4S9W3Sta+LaAyucO8irxHBGEdlgQlnTPRnnjscWa0sPLngdJMg+PMoyqiQYH1CfQqpBETtVVhEEsSgKT/IVHkUHCYKS8bYdqNlWrGQj6It9Wriun8KjXf7uDhp0KdJ5axV5qRw5hbcqFUmO/mIc475yAO6dV8vDROugL2IyFFhgx+vEp/qfNLpUIrVTGPBaMG20gSJvMV50W5bP9cGQ3N/QppNdbwvcvvTzQ3kRm/6MMx19BfyNL3sbbWUW9cZwUCHkxJF4WxJ/Er25wUqDWa4t7zDlm2aqlwd20E+8AOSFjO6vnD8p4wUizM/2iag8zMOgjIa+f/3jrT14zA18gEM8PpRA7eHqflbWWXxbEB9m9RS69JQQg184P5/ZJlAP1hf+8v/QweHHWc+/m7QYj9ZFXO37rC7kn2V78MZH5YjBc04jN8TvHug8L0BAiOepkE4roaGwiEh64gAALLGiLP9pL3ofzD5E0BksjBki/Ph4fFlJnu8cXjm2zRvaNkkyMJnjlUFNy7KPzAc4pAvQNSBBgqUTVYh/OqNeh60UKNSJIK7CS15Toy0vE/FVlJRXWPBQUNJ0GRGhrRmM+UK98knyrfHw1NlOlmKGXl0BRMA+HceDurwG7X50IH8+NwYmvQ/I6dnePVrWEg6WjroV7SKqTabAv49EVaHh2BfHdGwViqgVITr2qMGXFhrIbA6AKDbZlh0wv3D3ll6T7mGk3AUMc7nkB4Hncvr8nPSiaakfsElde/ZKdfVUXQGyU9estx2blg0eNo9m5cLPEmSaT428bTa5eaWuMASoezgrmV5e+wTWRMnHECN261LTKQs8ONn2Z14Om3rzMkhfmMVnYDjLAxBbDEyjP6v0/0g0csL6YdwNse5B2AI6AiHjyod5FtqVryE7NaIidqfyXDVz90jMckku40w7uOLeZhcxAaYFwXcGtw2SGALVdqMU615/m0yerb4lSoj156H4VeTxT+BYOxSSwdF71FoOt3O8OZg6UQ+tKHpB6ZnxCzYtqNQ7gH8dtYY90SE8V+fXtH7VFe7NAlItbCJJNFq8KrV4m8oFnha7hD/vw9Xddm2e6TJYm+leePn8aBcsQ2O2k17klf80bWtycuDzGg5cTwRXhS92NWmoZ2cHjEVgTBh6obHgYZL88gfryodQ0WNl2UzSizfSWmwxkzZPyuUzWSN6ERkO5wwjYgvxwjCIE+yeJvH4EgL5pI7qtrhdoCgp635+Bdbi004jnX1DdQaW/S++HHJIzQQcF70ydk8Ez1bHW7X2UawLW9F0jGtM8xoc5irna6nORnPXW+uUmevLqWlAkicqbmow62M8kmuAvNoMdSSukhV9zX27UbwPnZ2jSsm8ClmdIwA5BBcSm+bMLaJGRc+ev8WSc6STNrWLzmYKDL6qbhOFQ8uFXTrDMvBAe9aV+/6tULtQAQ90LylnEzJMeUHrWZg4cgyL/IVce3TxQrluLH6AHWBTaiaCo/Au884wu+dnpASuA4RJVP4gMhuSS6q4MoJZJEevOoZ1/eB1N4zehdat8akTOaP/zTXxWJ/+buMyShlz6Ol7nDJN27OdC9et8TA6utWvOwkAc5IrYbxqfWVypCenUVfKh5rYtDQ0+pf2idGHHsPdb00h60jdr0zXH97G1/ntWjOg/INqCWFp++f5tbzsbxrR1q09wxG9+3iRrM3PMkYyNGDASLkLga2fEhUGIhsvO+O82O9SzYIUCVMKDDP5LZ1MgaWr1ua5z3PaMXNvZcsoRJ4v7CxxcylSkmltAhP63pGC8/mpO2kY4579bfAHrv1xokOoQclKOuzR6OfHI2mtwE+ZN7qzUwSVE6XjZTt/XW7YZqVxHZxpwUXE/urL8ba/3X34kijLk8KzOG1MUoodQpamJl8gnRnWtwS7+qe00q1ou6Szs7eQpYnk125ogWupx4kgDNZiSkZcvVUZayplmPgtASjsyEYFadpvPO090daeoLLMk49qVP0ME/kVxQLgDskHDWBB+LS99HSvlI5jayCfKFhjW15UU7LWpg0nywK31d40voMwduc8dogRRWHfAT0ira/ZGyCfIeu6PTtZNnjFcgFVfrvA9XHDKUj1etwF31nnEiRQ+ocnm0WoXmyPyon083fbZnlN7j2y4cmo/I7xUQEdSYaJ1/wjfZEWiEFwstECRMSNSVmeVlaMkMGE+mTvJddqE+LwnZXndgVAnNjZAs3aieVkJjD9gTdaAvQYLNg+RngmrdgLJDzL21i3q6Hcr5Hylc8bW/VDtdAnJmKjwTdvJY2geJf/69uQ8To62OWEUZgJKAQmGZeBocL9W9t8ntYdPDdCQ/xN+PFi1XgedJR58/vSBeqxoEzygOQm6RpwXiF0DfdAF1jFJhyETp6DseQPEP2lETpVrFP1Pi68KfJop9joFPcFt9p16N8kELMMGdX1BipyMZX0NaA04umASMdavTCZdPLr2AkbdC2XCIQhJEX3idG09t2JjWByyhK3KpR2hYqDmHtsOGvuXcqNXRQqn0OpZd5OMs0+vjwJaQfrAOLnqDx8XxIJg0x3gXBQLXaZHefEj7uSpWBtzzhs3WhrN/OMkA8SeD8w7T7XUtTzLQrf4BN9go2s/w1g36Z6WweawKr0xmtBZtTNl8s3dVcEsCZ4CNeffa4mDEGp9l1yM09mnB1MJ0Ze1JzCIsAe3mhqp+ZG1KTTxnf9U2n71cbv4CzglnpP/IgjqRWQ/XqFenSlfcoi7gWjdmHDSUjbKc7UIf6NlOiDV7gXikKK9aqnrtgaHvf1qCrAWmAbvIJWcTnOgQWZuzKam/g/qJT1YLpo6+PxrTm+ZsT4xcHNoTFSEwfNCRdNS9zv19+B/+ApWHdDr78aVfQDvLBgB+F+aHR/vlBUmKUs1gOxr37GXqW93OTIEL96IlciF9OsEptZHBM9JzadrYjXpalbHJ4dvqM6kmX1/P+QqFa54qsatORnsYu9toXb/fCQX7zrOsgTMwWyV0EsNzp3PSkvaVfim3zwjsnzBORY/K/i/2cYvxfP92mSw4SNYPCkPpWB0g9eZK6p1LTD96NUGRQhF66YV7HMLhJRwIRDz0y9F5v+DiXyqmGvrwqbojgjsq9VDaynoDahFBejL6Jg/xMgfgC2DvG1dfrFeQmIXnGIbHJs95d6w+N4Mv71hIO/PU023VmsitVIDSN00KDK5Kn9OBsYJDLPnZBYBpBYxavEkn5n4FKrq/Gd1FLP7LUt1AWp8qey+4G2wz9oaZ1n+cGepzrYP7X5k4FuQyJmDPf0cBlJzJykt7ana6XAcyLh3JHVk/AnjXcdHjYnYFwqK68R86bhE9R+iXJArVhnCUbjUdYFwRz7Fg5MbUgYohJmdyAuUCA7cpQLYnHZ5qcm9jDaWuMDY61o0NIllvdKy0n/9u4aasms21vgTAbQMYKH1ygKcy6xjIoQKaXHM+TAUnHi6eeejApRQK+hvrfWWRPjZCJsTa4PO0NzG936F/BIyZVh+TU0bmfYUkbVB7pWePKof/SyMFqjafSxck0pvxxVeqDQkLyw/xCSz+lFkMgGbrzPc7BLdncuQ6dehYl3lzXlYzHWpZeLGCNmitV65R1d1NR51hMDbDDo8hvJyPn8OlzQunT399FMmjdF5IKHl1HO2Doq2qUAuc7OANxjbgUIRm0hqupUOYkyJL+5NWDTDNX2Wu2TkQEl+avnDhc/QJwSAXNyDZgN9pHFUQcrsGZ5Suw4cCFAcNvbOmpXdyLMuLrQ3cSe0rZLaY8WIRmusGDaHOneI6a6HvE3f0CCpYCTFe0R2gaiqYbHVgdEXkfrYsS5YgYxwHk2ij/5jRDuAmLOZfcdV1Bc8rG/5BQ7wNMdISL4chvFAfsMfZAkldQzHsP6cJWWAI8TaPdchgnfkIMDTEB//0syGzhighZ9rz+Vcp8h1Xm2RkALyjljpdNX+bA9hpi2lFU9FWDWUozf7HIrEI7BCwAWzbhlELuMsGMm2j1407LPdLzg4dzvH3OYI+DaP5iR5jU+FiZ7kM3DgT92Jf6iKfm+3k/u5Hha4R6dPrC89JSwUv96i/kMAU4jXC0kdwNssii7R08JXQocp66FFl0XhZoUn2yNYfCzIEGQCqb0kl6ptrjwihPpCgPDkIaq19NkphMhmNdDsT/HMZ4k5ZQtWWQzuMTcShBzOwz49jOprlt6BuUjKXQNF/PPh+WF9sFpRGxXdxtEb9cd4xGrgBGeUuwYo4PTP0x0Xm1FAilK25KyIUwR7wRBCb9FcDDin+UokEu3eyCMSgbybVOGKVrCV2Hr3VhRbpKhWN3sYds0VvBji5Wwee/7N2h8oMhVShVJ2Z4wNyHCAlY8KAKo0t10Coj+tiXMC4ly4r8PzNqRZJPvn4++PSJ6zCDtgEaK5wqzh6c9XgadARtNhKPLblcQS21g7xMDjxKVnAFYj2xAy1sFrw+Uo9ctN3poy4aqVe7LNYDyo97tUXq5VOHLwhBVUZJjOtkkofCGDdDIw7dXkMcIFGEJzMiAsua+zsGaQdHSFSM+0Ks0BVR41B0zr3Yahxbb23r2R1JisTpw2Ro4bnchWOqKvFD3EitHxH2Icj8ItvZXki25XhtUYWgTtZnOTz6Z3Xkqv8opC4QZsLIe7WOr6UbeigIG7Mz4MrTzd897YQhk9ZrXV+aMFotUz1pzpi1FdkrL/iu8UoShxjAZOPRjXa998r+BVOyt1Zw2pl+8kOa6gVvqFrgjPsGKIOgC3nudX0lUwy0VZ2bTlE8iMS06V2krGDDT+6IvB2BKWQMCdsq0IZ83qHEmffKQiMJhrfZVtO6JrO+UuoAu85CBWkXTwOQcVcuzaW2kCXLlkI6Jv4Dn06mrYYD5iRrvtMWkp2eWNq2Y3L0yUbpY20g7baO1eWtV3XRCu3ehC1H9S/TFBJu0/hrmh1jVBIUp6K6H5OQbNhN51HI+bJMw0Dx2ZFiTMs2mfM8LY3FVzk+Mk0k3rVBZUfbbIFdo4FJxBoamuWsept9YSRob1W/Hg1IeLXdzLGyRxaHOF8ILqMApDQ8ixwxS7PoJNw4BXMlRuaA23+1Rncb6eTL27fdS8HDzf8aXolSac+/qNHQc8ITTqrEEsBcJ324EeH6KzBZyfry8yeYOiqyA9ncZYZvsvKS/+eLHHFj9dRGx/TDVkDBkyeQWqN4GBS+4DKms6fXtpqKHLUGMUkB37v5bAYrnVCE8xs0/nRss9Ibh99YKEWvEE9YY+y626FMoaGGa3wWIzxwjhj5UTJOr26YS4VAUZHbge7ZLsBPURZfL7qDhUkTgJyVI3yzTDY+39L/7Ywxaw++hj5Trp9bor/ktjBtSp+hY5W7uIMx1nR4BP2McJBFp6/KZZYN6IOtee2fDe3K3ler70NIL3QpazHbUPJsTmQ==
---
kind: signature
hmac: 7c62f522f79ffd045612a0328b86cc3a4b8cf562f6cbf23c314e1fa06cf631f9

...
